# Generated by Django 5.2.10 on 2026-01-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetupload',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
