# Generated by Django 5.2.10 on 2026-01-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_datasetupload_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetupload',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datasetupload',
            name='summary',
            field=models.JSONField(default=dict),
        ),
    ]
